### ISSUE TITLE
Setup AWS for production

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/IGAD-C127#49]
We will use IGAD's AWS account to setup the following:

- [x] 1 EC2 for GeoNode
- [x] 1 EC2 for Geoserver
- [x] 1 RDS for GeoNode and Geoserver
- [x] 1 EFS for GeoNode and Geoserver data
- [ ] 1 S3 for backup data (static and DB dumps)

See [IGAD AWS doc](https://docs.google.com/document/d/19rHykajdtgCtzwD3Bkhx0Bqnl5XL2sO9nWMqKnCkJmg)

**Comment by randomorder** [comment]
Infrastructure set up and Documented. We used EFS to ackup GeoNode instead of S3
